kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: nim-nemo-guardrails
  version: 25.6.1
criteria:
  service: kind
  accelerator: any
  intent: inference
  os: rhel
  platform: none
componentRefs:
  - name: nemo-guardrails
    namespace: nim-nemo-guardrails
    chart: nemo-guardrails
    type: Helm
    source: https://helm.ngc.nvidia.com/nvidia/nemo-microservices/charts/nemo-guardrails-25.6.0.tgz
    version: 25.6.0
deploymentOrder:
  - nemo-guardrails
