kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: build-your-own
  version: 1.0.2
criteria:
  service: self-managed
  accelerator: h100
  intent: inference
  os: rhel
  platform: dynamo
componentRefs:
  - name: argo-workflows
    namespace: build-your-own
    chart: argo-workflows
    type: Helm
    source: oci://dp.apps.rancher.io/charts/argo-workflows
    version: *
  - name: vllm
    namespace: build-your-own
    chart: vllm
    type: Helm
    source: oci://dp.apps.rancher.io/charts/vllm
    version: *
  - name: opentelemetry-collector
    namespace: build-your-own
    chart: opentelemetry-collector
    type: Helm
    source: oci://dp.apps.rancher.io/charts/opentelemetry-collector
    version: *
deploymentOrder:
  - argo-workflows
  - vllm
  - opentelemetry-collector
