kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: build-your-own
  version: 1.0.2
criteria:
  service: kubernetes
  accelerator: any
  intent: mixed
  os: any
  platform: any
componentRefs:
  - name: ollama
    namespace: build-your-own
    chart: ollama
    type: Helm
    source: oci://dp.apps.rancher.io/charts/ollama
    version: '*'
  - name: live-vlm-webui
    namespace: build-your-own
    chart: live-vlm-webui
    type: Helm
    source: oci://dp.apps.rancher.io/charts/live-vlm-webui
    version: '*'
deploymentOrder:
  - ollama
  - live-vlm-webui
