global:
  imagePullSecrets:
    - application-collection
    - name: ngc-registry-secret
  namespace: ''
ollama:
  enabled: true
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  deployment:
    labels: {}
  extraArgs: []
  extraEnv: []
  extraEnvFrom: []
  extraObjects: []
  fullnameOverride: ''
  global:
    imagePullSecrets:
      - name: application-collection
      - name: ngc-registry-secret
    imageRegistry: ''
  hostIPC: false
  hostNetwork: false
  hostPID: false
  image:
    pullPolicy: IfNotPresent
    registry: dp.apps.rancher.io
    repository: containers/ollama
    tag: 0.14.2-11.17
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ''
    enabled: false
    hosts:
      - host: ollama.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  initContainers: []
  knative:
    annotations: {}
    containerConcurrency: 0
    enabled: false
    idleTimeoutSeconds: 300
    responseStartTimeoutSeconds: 300
    timeoutSeconds: 300
  lifecycle: {}
  livenessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 60
    path: /
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  nameOverride: ''
  namespaceOverride: ''
  nodeSelector: {}
  ollama:
    gpu:
      draDriverClass: gpu.nvidia.com
      draEnabled: false
      draExistingClaimTemplate: ''
      enabled: false
      mig:
        devices: {}
        enabled: false
      number: 1
      nvidiaResource: nvidia.com/gpu
      type: nvidia
    insecure: false
    models:
      clean: false
      create: []
      pull: []
      run: []
    mountPath: ''
    port: 11434
  persistentVolume:
    accessModes:
      - ReadWriteOnce
    annotations: {}
    enabled: false
    existingClaim: ''
    size: 30Gi
    storageClass: ''
    subPath: ''
    volumeMode: ''
    volumeName: ''
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  priorityClassName: ''
  readinessProbe:
    enabled: true
    failureThreshold: 6
    initialDelaySeconds: 30
    path: /
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
  replicaCount: 1
  resources:
    limits:
      cpu: 8000m
      memory: 10Gi
    requests:
      cpu: 2000m
      memory: 6Gi
  runtimeClassName: ''
  securityContext: {}
  service:
    annotations: {}
    ipFamilies: []
    ipFamilyPolicy: ''
    labels: {}
    loadBalancerIP: null
    nodePort: 31434
    port: 11434
    type: LoadBalancer
  serviceAccount:
    annotations: {}
    automount: true
    create: true
    name: ''
  terminationGracePeriodSeconds: 120
  tests:
    annotations: {}
    enabled: true
    labels: {}
  tolerations: []
  topologySpreadConstraints: {}
  updateStrategy:
    type: Recreate
  volumeMounts: []
  volumes: []
live-vlm-webui:
  enabled: true
