kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: build-your-own
  version: 1.0.1
criteria:
  service: kubernetes
  accelerator: any
  intent: mixed
  os: any
componentRefs:
  - name: nemo-guardrails
    namespace: build-your-own
    chart: nemo-guardrails
    type: Helm
    source: https://helm.ngc.nvidia.com/nvidia/nemo-microservices/charts/nemo-guardrails-25.6.0.tgz
    version: 25.6.0
deploymentOrder:
  - nemo-guardrails
