global:
  imagePullSecrets:
    - application-collection
    - ngc-registry-secret
  namespace: ''
nemo-guardrails:
  enabled: true
  replicaCount: 1
  image:
    repository: nvcr.io/nvidia/nemo-microservices/guardrails
    tag: ''
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: nvcrimagepullsecret
  nameOverride: ''
  fullnameOverride: ''
  guardrails:
    nvcfAPIKeySecretName: ''
  env:
    NIM_ENDPOINT_URL: https://integrate.api.nvidia.com/v1
    CONFIG_STORE_PATH: /app/services/guardrails/config-store
    DEFAULT_CONFIG_ID: default
    DEFAULT_LLM_PROVIDER: nim
    NEMO_GUARDRAILS_SERVER_ENABLE_CORS: 'False'
    NEMO_GUARDRAILS_SERVER_ALLOWED_ORIGINS: '*'
    GUARDRAILS_HOST: 0.0.0.0
    GUARDRAILS_PORT: '7331'
    DEMO: 'False'
  service:
    type: ClusterIP
    port: 7331
  configStore:
    nfs:
      enabled: false
      path: /path/to/nfs/share
      server: nfs-server.example.com
      mountPath: /config-store
      storageClass: standard
  readinessProbe:
    httpGet:
      path: /v1/health
      port: 7331
    initialDelaySeconds: 5
    timeoutSeconds: 30
  livenessProbe:
    httpGet:
      path: /v1/health
      port: 7331
    initialDelaySeconds: 5
    timeoutSeconds: 30
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ''
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  runAsGroup: ''
  fsGroup: ''
  securityContext: {}
  ingress:
    enabled: false
    className: ''
    annotations: {}
    hosts: {}
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
