global:
  imagePullSecrets:
    - application-collection
    - ngc-registry-secret
  namespace: ''
riva-nim:
  enabled: true
  affinity: {}
  containerSecurityContext: {}
  customCommand: []
  customArgs: []
  envVars: {}
  extraVolumes: {}
  extraVolumeMounts: {}
  image:
    repository: ''
    pullPolicy: IfNotPresent
    tag: latest
  imagePullSecrets:
    - name: ngc-secret
  initContainers: {}
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  replicaCount: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  serviceAccount:
    create: false
    annotations: {}
    name: ''
  schedulerName: ''
  statefulSet:
    enabled: false
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    metrics: []
  ingress:
    enabled: false
    className: ''
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  livenessProbe:
    enabled: true
    method: httpGet
    path: /v1/health/live
    initialDelaySeconds: 15
    timeoutSeconds: 10
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    enabled: true
    method: httpGet
    path: /v1/health/ready
    initialDelaySeconds: 15
    timeoutSeconds: 10
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    enabled: true
    method: httpGet
    path: /v1/health/ready
    initialDelaySeconds: 30
    timeoutSeconds: 10
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 480
  metrics:
    enabled: false
    port: 0
    serviceMonitor:
      enabled: false
      additionalLabels: {}
  nim:
    nimCache: /opt/nim/.cache
    modelName: ''
    ngcAPISecret: ngc-api
    ngcAPIKey: ''
    httpPort: 9000
    serverPort: 0
    grpcPort: 50051
    labels: {}
    jsonLogging: true
    logLevel: INFO
  persistence:
    enabled: false
    existingClaim: ''
    storageClass: ''
    accessMode: ReadWriteOnce
    stsPersistentVolumeClaimRetentionPolicy:
      whenDeleted: Retain
      whenScaled: Retain
    size: 50Gi
    annotations: {}
  hostPath:
    enabled: false
    path: /model-store
  nfs:
    enabled: false
    server: nfs-server.example.com
    path: /exports
    readOnly: false
  service:
    name: ''
    type: ClusterIP
    httpPort: 9000
    serverPort: 0
    grpcPort: 50051
    metricsPort: 0
    annotations: {}
    labels: {}
    nodePort: 0
  ingress_endpoint: {}
  egress_endpoint: {}
  params: {}
