kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: nim-google-gemma-3-1b-it
  version: 0.0.4
criteria:
  service: kubernetes
  accelerator: any
  intent: mixed
  os: any
  platform: any
componentRefs:
  - name: apache-airflow
    namespace: nim-google-gemma-3-1b-it
    chart: apache-airflow
    type: Helm
    source: oci://dp.apps.rancher.io/charts/apache-airflow
    version: '*'
  - name: ollama
    namespace: nim-google-gemma-3-1b-it
    chart: ollama
    type: Helm
    source: oci://dp.apps.rancher.io/charts/ollama
    version: '*'
  - name: google/gemma-3-1b-it
    namespace: nim-google-gemma-3-1b-it
    chart: google/gemma-3-1b-it
    type: Helm
    source: oci://dp.apps.rancher.io/charts/google/gemma-3-1b-it
    version: '*'
deploymentOrder:
  - apache-airflow
  - ollama
  - google/gemma-3-1b-it
