apiVersion: suse.ai/v1alpha1
kind: Blueprint
metadata:
  name: "nim-llm"
  labels:
    catalog.suse.ai/support: "opensource"
    catalog.suse.ai/tier: "certified"
    catalog.suse.ai/certified: "false"
    catalog.suse.ai/status: "new"
  mantainer: "alessandro.festa1@suse.com"
  source: "https://github.com/alessandro-festa/fleets"
spec:
  displayName: "nim-llm"
  description: "A Helm chart for NVIDIA NIM for LLMs"
  category: "Inference"
  source:
    git:
      url: "https://github.com/alessandro-festa/fleets"
      ref: "main"
      path: "nim-llm/1.15.5/chart"
  modules:
