global:
  imagePullSecrets:
    - application-collection
    - name: ngc-registry-secret
  namespace: ''
main:
  enabled: true
nv-ingest:
  enabled: true
eck-elasticsearch:
  enabled: true
zipkin:
  enabled: true
opentelemetry-collector:
  enabled: false
kube-prometheus-stack:
  enabled: true
