apiVersion: v2
name: nim-nvidia-vila
description: This is a simple demo
type: application
version: 0.0.2
appVersion: "1.0"
maintainers:
  - name: "@alessandro-festa"
keywords:
  - ai
  - ml
  - llm
  - suse-ai-factory

dependencies:
  - name: "vila"
    version: "1.6.0"
    repository: "https://helm.ngc.nvidia.com/nim/charts/nim-vlm-1.6.0.tgz"
    condition: "vila.enabled"

