apiVersion: v2
name: "husky-rigel"
description: ""
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "husky-rigel"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-04-03T13:44:04Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "argo-workflows"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: argo-workflows.enabled
