global:
  imagePullSecrets:
    - application-collection
  namespace: ''
milvus:
  enabled: true
  global:
    imageRegistry: ''
    imagePullSecrets: []
  nameOverride: ''
  fullnameOverride: ''
  cluster:
    enabled: true
  image:
    all:
      repository: containers/milvus
      tag: 2.6.11-2.6
      pullPolicy: IfNotPresent
      registry: dp.apps.rancher.io
  nodeSelector: {}
  tolerations: []
  affinity: {}
  containerSecurityContext: {}
  securityContext: {}
  topologySpreadConstraints: []
  labels: {}
  annotations: {}
  volumes: []
  volumeMounts: []
  streaming:
    enabled: true
    woodpecker:
      embedded: true
      storage:
        type: minio
  customConfigMap: ''
  extraConfigFiles:
    user.yaml: |+
      #    For example enable rest http for milvus proxy
      #    proxy:
      #      http:
      #        enabled: true
      #      maxUserNum: 100
      #      maxRoleNum: 10
      ##  Enable tlsMode and set the tls cert and key
      #  tls:
      #    serverPemPath: /etc/milvus/certs/tls.crt
      #    serverKeyPath: /etc/milvus/certs/tls.key
      #   common:
      #     security:
      #       tlsMode: 1

  service:
    type: ClusterIP
    port: 19530
    portName: milvus
    nodePort: ''
    annotations: {}
    labels: {}
    externalIPs: []
    loadBalancerSourceRanges:
      - 0.0.0.0/0
  ingress:
    enabled: false
    ingressClassName: ''
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
      nginx.ingress.kubernetes.io/listen-ports-ssl: '[19530]'
      nginx.ingress.kubernetes.io/proxy-body-size: 4m
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    labels: {}
    rules:
      - host: milvus-example.local
        path: /
        pathType: Prefix
    tls: []
  serviceAccount:
    create: false
    name: null
    annotations: null
    labels: null
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
      interval: 30s
      scrapeTimeout: 10s
      additionalLabels: {}
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  log:
    level: info
    file:
      maxSize: 300
      maxAge: 10
      maxBackups: 20
    format: text
    persistence:
      mountPath: /milvus/logs
      enabled: false
      annotations:
        helm.sh/resource-policy: keep
      persistentVolumeClaim:
        existingClaim: ''
        storageClass: null
        accessModes: ReadWriteMany
        size: 10Gi
        subPath: ''
  heaptrack:
    image:
      repository: containers/heaptrack
      tag: 1.3.0-2.1
      pullPolicy: IfNotPresent
      registry: dp.apps.rancher.io
  standalone:
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    disk:
      enabled: true
      size:
        enabled: false
    profiling:
      enabled: false
    messageQueue: woodpecker
    persistence:
      mountPath: /var/lib/milvus
      enabled: true
      annotations:
        helm.sh/resource-policy: keep
      persistentVolumeClaim:
        existingClaim: ''
        storageClass: null
        accessModes: ReadWriteOnce
        size: 50Gi
        subPath: ''
  proxy:
    enabled: true
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    http:
      enabled: true
      debugMode:
        enabled: false
    tls:
      enabled: false
    strategy: {}
    annotations: {}
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      cpuUtilization: 40
  rootCoordinator:
    enabled: false
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    activeStandby:
      enabled: false
    strategy: {}
    annotations: {}
    service:
      port: 53100
      annotations: {}
      labels: {}
      clusterIP: ''
  queryCoordinator:
    enabled: false
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    activeStandby:
      enabled: false
    strategy: {}
    annotations: {}
    service:
      port: 19531
      annotations: {}
      labels: {}
      clusterIP: ''
  queryNode:
    enabled: true
    replicas: 1
    resources: {}
    runtimeClassName: ''
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    disk:
      enabled: true
      size:
        enabled: false
    profiling:
      enabled: false
    strategy: {}
    annotations: {}
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      cpuUtilization: 40
      memoryUtilization: 60
  indexCoordinator:
    enabled: false
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    activeStandby:
      enabled: false
    strategy: {}
    annotations: {}
    service:
      port: 31000
      annotations: {}
      labels: {}
      clusterIP: ''
  indexNode:
    enabled: false
    replicas: 1
    resources: {}
    runtimeClassName: ''
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    disk:
      enabled: true
      size:
        enabled: false
    strategy: {}
    annotations: {}
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      cpuUtilization: 40
  dataCoordinator:
    enabled: false
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    activeStandby:
      enabled: false
    strategy: {}
    annotations: {}
    service:
      port: 13333
      annotations: {}
      labels: {}
      clusterIP: ''
  dataNode:
    enabled: true
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    strategy: {}
    annotations: {}
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      cpuUtilization: 40
  mixCoordinator:
    enabled: true
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    activeStandby:
      enabled: false
    strategy: {}
    annotations: {}
    service:
      annotations: {}
      labels: {}
      clusterIP: ''
  streamingNode:
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    strategy: {}
  cdc:
    enabled: false
    replicas: 1
    resources: {}
    nodeSelector: {}
    affinity: {}
    tolerations: []
    securityContext: {}
    containerSecurityContext: {}
    topologySpreadConstraints: []
    extraEnv: []
    heaptrack:
      enabled: false
    profiling:
      enabled: false
    strategy: {}
    annotations: {}
  externalS3:
    enabled: false
    host: ''
    port: ''
    accessKey: ''
    secretKey: ''
    useSSL: false
    bucketName: ''
    rootPath: ''
    useIAM: false
    cloudProvider: aws
    iamEndpoint: ''
    region: ''
    useVirtualHost: false
  externalGcs:
    bucketName: ''
  externalEtcd:
    enabled: false
    endpoints:
      - localhost:2379
  externalPulsar:
    enabled: false
    host: localhost
    port: 6650
    maxMessageSize: '5242880'
    tenant: public
    namespace: default
    authPlugin: ''
    authParams: ''
  externalKafka:
    enabled: false
    brokerList: localhost:9092
    securityProtocol: SASL_SSL
    sasl:
      mechanisms: PLAIN
      username: ''
      password: ''
  etcd:
    enabled: true
    name: etcd
    replicaCount: 3
    service:
      enabled: true
      annotations: {}
      type: ClusterIP
      nodePorts:
        client: '2379'
        peer: '2380'
      ports:
        client: '2379'
        peer: '2380'
    auth:
      rbac:
        enabled: false
    persistence:
      enabled: true
      storageClassName: null
      accessModes:
        - ReadWriteOnce
  kafka:
    enabled: true
    name: kafka
    broker:
      enabled: true
    cluster:
      nodeCount:
        broker: 3
        controller: 3
      listeners:
        client:
          protocol: PLAINTEXT
        controller:
          protocol: PLAINTEXT
  minio:
    enabled: true
    name: minio
    replicas: 4
    users:
      - accessKey: minioadmin
        secretKey: minioadmin
        existingSecret: ''
        policy: consoleAdmin
    bucketName: milvus-bucket
    rootPath: file
    useIAM: false
    iamEndpoint: ''
    region: ''
    useVirtualHost: false
    resources:
      requests:
        memory: 2Gi
open-webui:
  enabled: true
  global:
    imageRegistry: ''
    imagePullSecrets: []
    tls:
      source: suse-private-ai
      issuerName: suse-private-ai
      letsEncrypt:
        environment: staging
        email: none@example.com
        ingress:
          class: ''
      additionalTrustedCAs: false
  nameOverride: ''
  namespaceOverride: ''
  ollama:
    enabled: true
    fullnameOverride: open-webui-ollama
  ollamaUrls: []
  ollamaUrlsFromExtraEnv: false
  pipelines:
    enabled: false
    extraEnvVars: []
  tika:
    enabled: false
  websocket:
    enabled: true
    manager: redis
    url: redis://open-webui-redis:6379/0
    nodeSelector: {}
    redis:
      enabled: true
      name: open-webui-redis
      labels: {}
      annotations: {}
      pods:
        labels: {}
        annotations: {}
      image:
        registry: dp.apps.rancher.io
        repository: containers/redis
        tag: 8.4.0-2.1
        pullPolicy: IfNotPresent
      command: []
      args: []
      resources: {}
      service:
        containerPort: 6379
        type: ClusterIP
        labels: {}
        annotations: {}
        portName: http
        port: 6379
        nodePort: ''
      tolerations: []
      affinity: {}
      containerSecurityContext: {}
      podSecurityContext: {}
  clusterDomain: cluster.local
  extraLabels: {}
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  replicaCount: 1
  revisionHistoryLimit: 10
  priorityClassName: ''
  strategy: {}
  image:
    registry: dp.apps.rancher.io
    repository: containers/open-webui
    tag: 0.6.41-14.20
    pullPolicy: IfNotPresent
    useSlim: false
  imagePullSecrets: []
  command: []
  args: []
  serviceAccount:
    enable: true
    create: true
    name: existing-sa
    annotations: {}
    automountServiceAccountToken: false
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  resources: {}
  copyAppData:
    command: []
    args: []
    resources: {}
  managedCertificate:
    enabled: false
    name: mydomain-chat-cert
    domains:
      - chat.example.com
  ingress:
    enabled: true
    class: ''
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    host: ''
    additionalHosts: []
    tls: true
    existingSecret: ''
    extraLabels: {}
  persistence:
    enabled: true
    size: 2Gi
    existingClaim: ''
    subPath: ''
    accessModes:
      - ReadWriteOnce
    storageClass: ''
    selector: {}
    annotations: {}
    provider: local
    s3:
      accessKey: ''
      secretKey: ''
      accessKeyExistingSecret: ''
      accessKeyExistingAccessKey: ''
      secretKeyExistingSecret: ''
      secretKeyExistingSecretKey: ''
      endpointUrl: ''
      region: ''
      bucket: ''
      keyPrefix: ''
    gcs:
      appCredentialsJson: ''
      appCredentialsJsonExistingSecret: ''
      appCredentialsJsonExistingSecretKey: ''
      bucket: ''
    azure:
      endpointUrl: ''
      container: ''
      key: ''
      keyExistingSecret: ''
      keyExistingSecretKey: ''
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
  hostAliases: []
  service:
    type: ClusterIP
    annotations: {}
    port: 80
    containerPort: 8080
    nodePort: ''
    labels: {}
    loadBalancerClass: ''
  enableOpenaiApi: true
  openaiBaseApiUrl: https://api.openai.com/v1
  openaiBaseApiUrls: []
  openaiApiKey: 0p3n-w3bu!
  openaiApiKeys: []
  databaseUrl: ''
  extraEnvVars: []
  commonEnvVars: []
  extraEnvFrom: []
  runtimeClassName: ''
  volumeMounts:
    initContainer: []
    container: []
  extraInitContainers: []
  volumes: []
  podSecurityContext: {}
  containerSecurityContext: {}
  sso:
    enabled: false
    enableSignup: false
    mergeAccountsByEmail: false
    enableRoleManagement: false
    enableGroupManagement: false
    google:
      enabled: false
      clientId: ''
      clientSecret: ''
      clientExistingSecret: ''
      clientExistingSecretKey: ''
    microsoft:
      enabled: false
      clientId: ''
      clientSecret: ''
      clientExistingSecret: ''
      clientExistingSecretKey: ''
      tenantId: ''
    github:
      enabled: false
      clientId: ''
      clientSecret: ''
      clientExistingSecret: ''
      clientExistingSecretKey: ''
    oidc:
      enabled: false
      clientId: ''
      clientSecret: ''
      clientExistingSecret: ''
      clientExistingSecretKey: ''
      providerUrl: ''
      providerName: SSO
      scopes: openid email profile
    roleManagement:
      rolesClaim: roles
      allowedRoles: ''
      adminRoles: ''
    groupManagement:
      groupsClaim: groups
    trustedHeader:
      enabled: false
      emailHeader: ''
      nameHeader: ''
  extraResources: []
  logging:
    level: ''
    components:
      audio: ''
      comfyui: ''
      config: ''
      db: ''
      images: ''
      main: ''
      models: ''
      ollama: ''
      openai: ''
      rag: ''
      webhook: ''
vllm:
  enabled: true
  global:
    imageRegistry: ''
    imagePullSecrets: []
  servingEngineSpec:
    enableEngine: true
    labels:
      environment: test
      release: test
    modelSpec: []
    containerPort: 8000
    servicePort: 80
    configs: {}
    strategy: {}
    startupProbe:
      initialDelaySeconds: 15
      periodSeconds: 10
      failureThreshold: 60
      httpGet:
        path: /health
        port: 8000
    livenessProbe:
      initialDelaySeconds: 15
      failureThreshold: 3
      periodSeconds: 10
      httpGet:
        path: /health
        port: 8000
    maxUnavailablePodDisruptionBudget: ''
    tolerations: []
    runtimeClassName: nvidia
    schedulerName: ''
    securityContext: {}
    containerSecurityContext:
      runAsNonRoot: false
  routerSpec:
    repository: containers/lmcache-lmstack-router
    tag: 0.1.6-3.20
    imagePullPolicy: Always
    enableRouter: true
    replicaCount: 1
    containerPort: 8000
    serviceType: ClusterIP
    serviceAnnotations: {}
    servicePort: 80
    serviceDiscovery: k8s
    staticBackends: ''
    staticModels: ''
    routingLogic: roundrobin
    sessionKey: ''
    extraArgs: []
    engineScrapeInterval: 15
    requestStatsWindow: 60
    strategy: {}
    resources:
      requests:
        cpu: '4'
        memory: 16G
      limits:
        cpu: '8'
        memory: 32G
    labels:
      environment: router
      release: router
    ingress:
      enabled: false
      className: ''
      annotations: {}
      hosts:
        - host: vllm-router.local
          paths:
            - path: /
              pathType: Prefix
      tls: []
    nodeSelectorTerms: []
    registry: dp.apps.rancher.io
  loraController:
    enableLoraController: false
open-webui-mcpo:
  enabled: true
  global:
    imageRegistry: ''
    imagePullSecrets: []
  replicaCount: 1
  image:
    registry: dp.apps.rancher.io
    repository: containers/open-webui-mcpo
    pullPolicy: IfNotPresent
    tag: 0.0.17-2.18
  imagePullSecrets: []
  nameOverride: ''
  fullnameOverride: ''
  serviceAccount:
    create: true
    annotations: {}
    name: ''
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000
  ingress:
    enabled: false
    className: ''
    annotations: {}
    path: /
    pathType: Prefix
    hosts:
      - open-webui-mcpo.local
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: {}
  envSecrets: {}
  secretEnv:
    data: {}
  config:
    mcpServers:
      memory:
        command: npx
        args:
          - '-y'
          - '@modelcontextprotocol/server-memory'
suse-ai-minimal:
  enabled: true
open-webui-pipelines:
  enabled: true
  global:
    imageRegistry: ''
    imagePullSecrets: []
  nameOverride: ''
  namespaceOverride: ''
  clusterDomain: cluster.local
  extraLabels: {}
  annotations: {}
  podAnnotations: {}
  podLabels: {}
  replicaCount: 1
  strategy: {}
  image:
    registry: dp.apps.rancher.io
    repository: containers/open-webui-pipelines
    tag: 0.20250819.030501-8.19
    pullPolicy: Always
  imagePullSecrets: []
  resources: {}
  ingress:
    enabled: true
    class: ''
    annotations: {}
    host: ''
    tls: false
    existingSecret: ''
  persistence:
    enabled: true
    size: 2Gi
    existingClaim: ''
    accessModes:
      - ReadWriteOnce
    storageClass: ''
    selector: {}
    annotations: {}
  serviceAccount:
    enable: true
    automountServiceAccountToken: false
  podSecurityContext: {}
  containerSecurityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  hostAliases: []
  service:
    type: ClusterIP
    annotations: {}
    port: 9099
    containerPort: 9099
    nodePort: ''
    labels: {}
    loadBalancerClass: ''
  extraEnvVars:
    - name: PIPELINES_URLS
      value: https://github.com/open-webui/pipelines/blob/main/examples/filters/detoxify_filter_pipeline.py
  commonEnvVars: []
  volumeMounts: []
  extraInitContainers: []
  volumes: []
  extraResources: []
