apiVersion: suse.ai/v1alpha1
kind: Blueprint
metadata:
  name: "my-simple-stack"
  labels:
    catalog.suse.ai/support: "opensource"
    catalog.suse.ai/tier: "community/custom"
    catalog.suse.ai/certified: "false"
    catalog.suse.ai/status: "new"
  maintainer: "alessandro.festa1@suse.com"
  source: "https://github.com/alessandro-festa/fleets"
  icon: ../icon.png
spec:
  displayName: "my-simple-stack"
  description: "This is a simple stack created by me"
  category: "Inference"
  source:
    git:
      url: "https://github.com/alessandro-festa/fleets"
      ref: "main"
      path: "my-simple-stack/0.0.1"
  modules:
    - moduleRef: "argo-workflows"
      displayName: "Argo Workflows"
      description: "Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. Argo Workflows is implemented as a Kubernetes CRD (Custom Resource Definition)."
      category: "dataIngestion"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/argo-workflows"
          ref: ">0.0.0-0"
      targetNamespace: "my-simple-stack"
    - moduleRef: "google-gemma-3-1b-it"
      displayName: ""
      description: "Inference model: google/gemma-3-1b-it"
      category: "inference"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/google-gemma-3-1b-it"
          ref: ">0.0.0-0"
      targetNamespace: "my-simple-stack"
    - moduleRef: "opentelemetry-collector"
      displayName: "OpenTelemetry Collector"
      description: "The OpenTelemetry Collector offers a vendor-agnostic implementation on how to receive, process and export telemetry data. In addition, it removes the need to run, operate and maintain multiple agents/collectors in order to support open-source telemetry data formats (e.g. Jaeger, Prometheus, etc.) to multiple open-source or commercial back-ends."
      category: "applicationUI"
      support: "SUSE"
      source:
        helm:
          url: "oci://dp.apps.rancher.io/charts/opentelemetry-collector"
          ref: ">0.0.0-0"
      targetNamespace: "my-simple-stack"