apiVersion: v2
name: "my-simple-stack"
description: "This is a simple stack description"
version: "0.0.2"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "my-simple-stack"
  blueprint.suse.ai/version: "0.0.2"
  blueprint.suse.ai/last-edit: "2026-03-24T11:36:46Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "argo-workflows"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: argo-workflows.enabled
  - name: "ollama"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: ollama.enabled
