kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: nvidia-blueprint-rag
  version: v2.4.3
criteria:
  service: self-managed
  accelerator: h100
  intent: inference
  os: rhel
  platform: dynamo
componentRefs:
  - name: milvus
    namespace: nvidia-blueprint-rag
    chart: milvus
    type: Helm
    source: oci://dp.apps.rancher.io/charts/milvus
    version: *
  - name: redis
    namespace: nvidia-blueprint-rag
    chart: redis
    type: Helm
    source: oci://dp.apps.rancher.io/charts/redis
    version: *
  - name: eck-elasticsearch
    namespace: nvidia-blueprint-rag
    chart: eck-elasticsearch
    type: Helm
    source: oci://dp.apps.rancher.io/charts/eck-elasticsearch
    version: *
  - name: zipkin
    namespace: nvidia-blueprint-rag
    chart: zipkin
    type: Helm
    source: oci://dp.apps.rancher.io/charts/zipkin
    version: *
  - name: opentelemetry-collector
    namespace: nvidia-blueprint-rag
    chart: opentelemetry-collector
    type: Helm
    source: oci://dp.apps.rancher.io/charts/opentelemetry-collector
    version: *
  - name: kube-prometheus-stack
    namespace: nvidia-blueprint-rag
    chart: kube-prometheus-stack
    type: Helm
    source: oci://dp.apps.rancher.io/charts/kube-prometheus-stack
    version: *
deploymentOrder:
  - milvus
  - redis
  - eck-elasticsearch
  - zipkin
  - opentelemetry-collector
  - kube-prometheus-stack
