global:
  imagePullSecrets:
    - application-collection
    - name: ngc-registry-secret
  namespace: ''
milvus:
  enabled: true
redis:
  enabled: true
eck-elasticsearch:
  enabled: true
zipkin:
  enabled: true
opentelemetry-collector:
  enabled: true
kube-prometheus-stack:
  enabled: true
