kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: build-your-own
  version: 1.0.1
criteria:
  service: kubernetes
  accelerator: any
  intent: mixed
  os: any
  platform: any
componentRefs:
  - name: argo-workflows
    namespace: build-your-own
    chart: argo-workflows
    type: Helm
    source: oci://dp.apps.rancher.io/charts/argo-workflows
    version: '*'
deploymentOrder:
  - argo-workflows
