kind: RecipeResult
apiVersion: aicr.nvidia.com/v1alpha1
metadata:
  name: build-your-own
  version: 1.0.1
criteria:
  service: kubernetes
  accelerator: any
  intent: mixed
  os: any
  platform: any
componentRefs:
  - name: ollama
    namespace: build-your-own
    chart: ollama
    type: Helm
    source: oci://dp.apps.rancher.io/charts/ollama
    version: '*'
  - name: custom-1773856840512
    namespace: build-your-own
    chart: custom-1773856840512
    type: Helm
    source: oci://dp.apps.rancher.io/charts/custom-1773856840512
    version: '*'
deploymentOrder:
  - ollama
  - custom-1773856840512
