global:
  imagePullSecrets:
    - application-collection
  namespace: ''
searchqna:
  enabled: true
  replicaCount: 1
  image:
    repository: opea/searchqna
    tag: latest
  imagePullSecrets: []
  nameOverride: ''
  fullnameOverride: ''
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ''
  podAnnotations: {}
  podSecurityContext: {}
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  port: 8888
  service:
    type: ClusterIP
    port: 3008
  nodeSelector: {}
  tolerations: []
  affinity: {}
  tgi:
    LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
  llm-uservice:
    LLM_MODEL_ID: Intel/neural-chat-7b-v3-3
  web-retriever:
    GOOGLE_API_KEY: insert-your-google-api-key-here
    GOOGLE_CSE_ID: insert-your-google-search-engine-id-here
  nginx:
    service:
      type: NodePort
  searchqna-ui:
    image:
      repository: opea/searchqna-ui
      tag: latest
    BACKEND_SERVICE_ENDPOINT: /v1/searchqna
    containerPort: 5173
  global:
    http_proxy: ''
    https_proxy: ''
    no_proxy: ''
    HF_TOKEN: insert-your-huggingface-token-here
    sharedSAName: searchqna
    modelUseHostPath: ''
    monitoring: false
    prometheusRelease: prometheus-stack
tei:
  enabled: true
embedding-usvc:
  enabled: true
web-retriever:
  enabled: true
teirerank:
  enabled: true
reranking-usvc:
  enabled: true
tgi:
  enabled: true
llm-uservice:
  enabled: true
ui:
  enabled: true
nginx:
  enabled: true
