apiVersion: v2
name: "nemo-guardrails"
description: "NeMo Guardrails Microservice Helm Chart"
version: "25.6.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "nemo-guardrails"
  blueprint.suse.ai/version: "25.6.1"
  blueprint.suse.ai/last-edit: "2026-03-23T18:35:20Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "nim-llm"
    version: "1.15.5"
    repository: "oci://nvcr.io/nim/nvidia"
    condition: google-gemma-3-1b-it.enabled
