apiVersion: v2
name: "dalmatian-uranus"
description: "A very simple bundle"
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "dalmatian-uranus"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-04-03T14:01:37Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "argo-workflows"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: argo-workflows.enabled
  - name: "ollama"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: ollama.enabled
