apiVersion: suse.ai/v1alpha1
kind: Blueprint
metadata:
  name: my-stack-0.0.1
  labels:
    catalog.suse.ai/support: opensource
    catalog.suse.ai/tier: certified
    catalog.suse.ai/certified: "false"
    catalog.suse.ai/status: new
  mantainer: alessandro.festa1@suse.com
  source: https://github.com/alessandro-festa/fleets/
spec:
  displayName: my-stack-0.0.1
  description: A simple description text
  category: Inference
  source:
    git:
      url: https://github.com/alessandro-festa/fleets/
      ref: main
      path: my-stack-0.0.1/0.0.2
  modules:
    - moduleRef: apache-airflow
      displayName: Apache Airflow
      description: Apache Airflow is an open-source platform for programmatically authoring, scheduling, and monitoring complex workflows, primarily used for data pipelines, but also for other automated tasks like infrastructure management.
      category: dataIngestion
      support: SUSE
      source:
        helm:
          url: oci://dp.apps.rancher.io/charts/apache-airflow
          ref: latest
      targetNamespace: my-stack-0.0.1
    - moduleRef: open-webui
      displayName: Open WebUI
      description: Open WebUI is an extensible, feature-rich, and user-friendly self-hosted WebUI designed to operate entirely offline. It supports various LLM runners, including Ollama and OpenAI-compatible APIs.
      category: applicationUI
      support: SUSE
      source:
        helm:
          url: oci://dp.apps.rancher.io/charts/open-webui
          ref: latest
      targetNamespace: my-stack-0.0.1