# Author: alex
# Date: 2026-03-19T18:47:19Z
# Version: 0.0.1
# Stack Name: my-stack-0.0.1

# Aggregated Stack Configuration



# =============================================================================
# --- Custom Container: vlm ---
# =============================================================================
vlm:
  image:
    repository: ghcr.io/nvidia-ai-iot/live-vlm-webui
    tag: latest
  service:
    port: 80
  
