apiVersion: v2
name: nvidia-blueprint-rag
description: An end to end Helm chart for the NVIDIA RAG Blueprint
type: application
version: v2.4.1
appVersion: "1.0"
keywords:
  - ai
  - ml
  - llm
  - suse-ai-factory

dependencies:
  - name: "nvidia-blueprint-rag"
    version: "v2.4.0"
    repository: "oci://https://github.com/NVIDIA-AI-Blueprints/rag/deploy/helm/nvidia-blueprint-rag"
    condition: "nvidia-blueprint-rag.enabled"
  - name: "nv-ingest"
    version: "*"
    repository: "oci://dp.apps.rancher.io/charts/nv-ingest"
    condition: "nv-ingest.enabled"
  - name: "eck-elasticsearch"
    version: "*"
    repository: "oci://dp.apps.rancher.io/charts/eck-elasticsearch"
    condition: "eck-elasticsearch.enabled"
  - name: "zipkin"
    version: "*"
    repository: "oci://dp.apps.rancher.io/charts/zipkin"
    condition: "zipkin.enabled"
  - name: "opentelemetry-collector"
    version: "*"
    repository: "oci://dp.apps.rancher.io/charts/opentelemetry-collector"
    condition: "opentelemetry-collector.enabled"
  - name: "kube-prometheus-stack"
    version: "*"
    repository: "oci://dp.apps.rancher.io/charts/kube-prometheus-stack"
    condition: "kube-prometheus-stack.enabled"

