apiVersion: v2
name: "mastiff-scheat"
description: ""
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "mastiff-scheat"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-03-25T14:00:52Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "apache-airflow"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: apache-airflow.enabled
  - name: "nim-llm"
    version: "1.15.5"
    repository: "https://helm.ngc.nvidia.com/nim"
    condition: google-gemma-3-1b-it.enabled
  - name: "opentelemetry-collector"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: opentelemetry-collector.enabled
