apiVersion: suse.ai/v1alpha1
kind: Blueprint
metadata:
  name: "bulldog-proxima"
  labels:
    catalog.suse.ai/support: "opensource"
    catalog.suse.ai/tier: "certified"
    catalog.suse.ai/certified: "false"
    catalog.suse.ai/status: "new"
  mantainer: "alessandro.festa1@suse.com"
  source: "https://github.com/alessandro-festa/fleets"
spec:
  displayName: "bulldog-proxima"
  description: ""
  category: "Inference"
  source:
    git:
      url: "https://github.com/alessandro-festa/fleets"
      ref: "main"
      path: "bulldog-proxima/0.0.1/chart"
  modules:
    - moduleRef: "google-gemma-3-1b-it"
      displayName: ""
      description: "Inference model: google/gemma-3-1b-it"
      category: "inference"
      support: "NVIDIA"
      source:
        helm:
          url: "https://helm.ngc.nvidia.com/nim/charts/nim-llm-1.15.5.tgz"
          ref: ">0.0.0-0"
          path: ""
      targetNamespace: "bulldog-proxima"