apiVersion: v2
name: nvidia-blueprint-rag
version: v2.5.0
description: An end to end Helm chart for the NVIDIA RAG Blueprint
type: application
icon: https://github.com/NVIDIA-AI-Blueprints.png
maintainers:
  - name: a
dependencies:
  - name: nvidia-blueprint-rag
    version: v2.5.0
    repository: oci://dp.apps.rancher.io/charts/nvidia-blueprint-rag
    condition: nvidia-blueprint-rag.enabled
  - name: opentelemetry-collector
    version: 0.130.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
