apiVersion: v2
name: "kuvasz-markab"
description: ""
version: "0.0.1"
appVersion: "1.0"
type: application
annotations:
  blueprint.suse.ai/name: "kuvasz-markab"
  blueprint.suse.ai/version: "0.0.1"
  blueprint.suse.ai/last-edit: "2026-03-27T15:23:37Z"
  blueprint.suse.ai/authors: "alessandro.festa1@suse.com"
dependencies:
  - name: "argo-workflows"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: argo-workflows.enabled
  - name: "ollama"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: ollama.enabled
  - name: "pytorch"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: pytorch.enabled
  - name: "open-webui"
    version: ">0.0.0-0"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: open-webui.enabled
