global:
  imagePullSecrets:
    - application-collection
  namespace: ''
clearml:
  enabled: true
  global:
    imageRegistry: docker.io
  imageCredentials:
    enabled: false
    existingSecret: ''
    registry: docker.io
    username: someone
    password: pwd
    email: someone@host.com
  clearml:
    cookieName: clearml-token-k8s
    cookieDomain: ''
    defaultCompany: d1bd92a3b039400cbafc60a7a5b1e52b
    apiserverKey: GGS9F4M6XB2DXJ5AFT9F
    apiserverSecret: 2oGujVFhPfaozhpuz2GzQfA5OyxmMsR3WVJpsCR5hrgHFs20PO
    fileserverKey: XXCRJ123CEE2KSQ068WO
    fileserverSecret: YIy8EVAC7QCT4FtgitxAQGyW7xRHDZ4jpYlTE7HKiscpORl1hG
    readinessprobeKey: GK4PRTVT3706T25K6BA1
    readinessprobeSecret: ymLh1ok5k5xNUQfS944Xdx9xjf0wueokqKM2dMZfHuH9ayItG2
    secureAuthTokenSecret: ymLh1ok5k5xNUQfS944Xdx9xjf0wueokqKM2dMZfHuH9ayItG2
    testUserKey: ENP39EQM4SLACGD5FXB7
    testUserSecret: lPcm0imbcBZ8mwgO7tpadutiS3gnJD05x9j7afwXPS35IKbpiQ
    clientConfigurationApiUrl: ''
    clientConfigurationFilesUrl: ''
    existingSecret: ''
  apiserver:
    enabled: true
    deploymentAnnotations: null
    prepopulateEnabled: true
    serviceAccountName: clearml
    serviceAccountAnnotations: {}
    image:
      registry: ''
      repository: allegroai/clearml
      pullPolicy: IfNotPresent
      tag: 2.0.0-613
    service:
      annotations: {}
      type: NodePort
      port: 8008
      nodePort: 30008
    replicaCount: 1
    initContainers:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 10m
          memory: 64Mi
    ingress:
      enabled: false
      ingressClassName: ''
      hostName: api.clearml.127-0-0-1.nip.io
      tlsSecretName: ''
      annotations: {}
      path: /
    processes:
      count: 8
      timeout: 24000
      maxRequests: 1000
      maxRequestsJitter: 300
    extraEnvs: []
    podAnnotations: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    containerSecurityContext: {}
    existingAdditionalConfigsConfigMap: ''
    existingAdditionalConfigsSecret: ''
    additionalConfigs: {}
    additionalVolumes: {}
    additionalVolumeMounts: {}
    asyncdelete:
      extraEnvs: []
  fileserver:
    enabled: true
    deploymentAnnotations: {}
    serviceAccountName: clearml
    serviceAccountAnnotations: {}
    image:
      registry: ''
      repository: allegroai/clearml
      pullPolicy: IfNotPresent
      tag: 2.0.0-613
    service:
      annotations: {}
      type: NodePort
      port: 8081
      nodePort: 30081
    replicaCount: 1
    initContainers:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 10m
          memory: 64Mi
    ingress:
      enabled: false
      ingressClassName: ''
      hostName: files.clearml.127-0-0-1.nip.io
      tlsSecretName: ''
      annotations: {}
      path: /
    extraEnvs: []
    podAnnotations: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    containerSecurityContext: {}
    storage:
      enabled: true
      data:
        existingPVC: ''
        class: ''
        accessMode: ReadWriteOnce
        size: 50Gi
    additionalVolumes: {}
    additionalVolumeMounts: {}
  webserver:
    enabled: true
    deploymentAnnotations: {}
    serviceAccountName: clearml
    serviceAccountAnnotations: {}
    image:
      registry: ''
      repository: allegroai/clearml
      pullPolicy: IfNotPresent
      tag: 2.0.0-613
    service:
      annotations: {}
      type: NodePort
      port: 8080
      nodePort: 30080
    replicaCount: 1
    initContainers:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 10m
          memory: 64Mi
    ingress:
      enabled: false
      ingressClassName: ''
      hostName: app.clearml.127-0-0-1.nip.io
      tlsSecretName: ''
      annotations: {}
      path: /
    extraEnvs: []
    podAnnotations: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 1Gi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext: {}
    containerSecurityContext: {}
    additionalConfigs: {}
    additionalVolumes: {}
    additionalVolumeMounts: {}
  externalServices:
    elasticsearchConnectionString: '[{"host":"es_hostname1","port":9200},{"host":"es_hostname2","port":9200},{"host":"es_hostname3","port":9200}]'
    mongodbConnectionStringAuth: mongodb://mongodb_hostname:27017/auth
    mongodbConnectionStringBackend: mongodb://mongodb_hostnamehostname:27017/backend
    redisHost: redis_hostname
    redisPort: 6379
  redis:
    enabled: true
    image:
      repository: bitnamilegacy/redis
    auth:
      enabled: false
    databaseNumber: 0
    master:
      name: '{{ .Release.Name }}-redis-master'
      port: 6379
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 5Gi
        storageClass: null
    architecture: standalone
  mongodb:
    enabled: true
    image:
      repository: bitnamilegacy/mongodb
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
    architecture: standalone
    auth:
      enabled: false
    replicaCount: 1
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 50Gi
      storageClass: null
  elasticsearch:
    enabled: true
    httpPort: 9200
    roles:
      master: 'true'
      ingest: 'true'
      data: 'true'
      remote_cluster_client: 'true'
    replicas: 1
    clusterHealthCheckParams: wait_for_status=yellow&timeout=1s
    rbac:
      create: true
    minimumMasterNodes: 1
    clusterName: clearml-elastic
    esJavaOpts: '-Xmx2g -Xms2g'
    extraEnvs:
      - name: bootstrap.memory_lock
        value: 'false'
      - name: cluster.routing.allocation.node_initial_primaries_recoveries
        value: '500'
      - name: cluster.routing.allocation.disk.watermark.low
        value: 500mb
      - name: cluster.routing.allocation.disk.watermark.high
        value: 500mb
      - name: cluster.routing.allocation.disk.watermark.flood_stage
        value: 500mb
      - name: http.compression_level
        value: '7'
      - name: reindex.remote.whitelist
        value: '*.*'
      - name: xpack.monitoring.enabled
        value: 'false'
      - name: xpack.security.enabled
        value: 'false'
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    persistence:
      enabled: true
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: null
      resources:
        requests:
          storage: 50Gi
    esConfig:
      elasticsearch.yml: |
        xpack.security.enabled: false
redis:
  enabled: true
mongodb:
  enabled: true
elasticsearch:
  enabled: true
