apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.service }}{{ .Values.service.type | default "ClusterIP" }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ if .Values.service }}{{ .Values.service.port | default 80 }}{{ else }}80{{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
