apiVersion: v2
name: suse-ai-minimal
description: A Meta Helm chart for deploying SUSE AI components
type: application
version: 1.2.1
appVersion: "1.0"
keywords:
  - ai
  - ml
  - llm
  - suse-ai-factory

dependencies:
  - name: "suse-ai-minimal"
    version: "1.2.0"
    repository: "oci://https://github.com/alessandro-festa/rd-nv-suseai/charts/suse-ai-minimal"
    condition: "suse-ai-minimal.enabled"
  - name: "milvus"
    version: "5.0.13"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: "milvus.enabled"
  - name: "ollama"
    version: "1.33.2"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: "ollama.enabled"
  - name: "open-webui"
    version: "8.19.1"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: "open-webui.enabled"
  - name: "pytorch"
    version: "0.3.2"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: "pytorch.enabled"
  - name: "vllm"
    version: "0.1.6"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: "vllm.enabled"
  - name: "open-webui-mcpo"
    version: "1.0.2"
    repository: "oci://dp.apps.rancher.io/charts"
    condition: "open-webui-mcpo.enabled"

